### ISSUE TITLE
Trying to implement REFEDS MFA support

### ISSUE THREAD

**Issue by jbstowe** [Unicon/shib-cas-authn#4]
Hi,

I followed the instructions to enable the native REFEDS MFA support and then rebuilt/redpeloyed the war but I am getting the following error when trying to login:

2021-08-13 16:59:15,909 - ERROR [org.springframework.web.util.NestedServletException:74] -
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.AbstractMethodError: Receiver class net.unicon.idp.externalauth.CasDuoSecurityRefedsAuthnMethodTranslator$1$1 does not define or inherit an implementation of the resolved method 'boolean test(java.lang.Object)' of interface net.shibboleth.idp.authn.principal.PrincipalEvalPredicate.
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
Caused by: java.lang.AbstractMethodError: Receiver class net.unicon.idp.externalauth.CasDuoSecurityRefedsAuthnMethodTranslator$1$1 does not define or inherit an implementation of the resolved method 'boolean test(java.lang.Object)' of interface net.shibboleth.idp.authn.principal.PrincipalEvalPredicate.
        at net.shibboleth.idp.authn.impl.FinalizeAuthentication.findMatchingPrincipal(FinalizeAuthentication.java:247)

Any help would be much appreciated, thanks!

**Comment by pspaude** [comment]
What version of Shibboleth IdP and what version of this plugin are you using? 

That error should be resolved in the latest plugin unless 4.1.x has changed in some way: https://github.com/Unicon/shib-cas-authn/blob/3c3a762317d9a61ed5b865a921d4cf9fefa3e93b/src/main/java/net/unicon/idp/externalauth/CasDuoSecurityRefedsAuthnMethodTranslator.java#L107

**Comment by pspaude** [comment]
Hopefully the previous comment solved your issue. If you continue to have issues feel free to reach out.
